export default [
  {
    link: 'https://bilitool.org/',
    imageURL: '/images/bile.png',
    imageAlt: 'CADDRA Logo',
    title: 'BiliTool',
    description: 'Newborn Bilirubin Nomogram and Guideline.',
  },
  {
    link: 'https://www.trustee.bc.ca/reports-and-publications/Pages/certificate-of-incapability-guidelines.aspx',
    imageURL: '/images/PGT.jpg',
    imageAlt: 'PGT Logo',
    title: 'Certificate of Incapability and Guidelines',
    description: '',
  },
  {
    link: 'https://www.assign-score.com/estimate-the-risk/',
    imageURL: '/images/Assign.png',
    imageAlt: 'ASSIGN SCORE Logo',
    title: 'Cardiovascular Risk Assessment',
    description: 'ASSIGN Score.',
  },
  {
    link: 'https://chd.bestsciencemedicine.com/calc2.html',
    imageURL: '/images/heartBeatCrimsonIcon.jpg',
    imageAlt: 'Cardiac Risk',
    title: 'Cardiovascular Risk Assessment',
    description: 'CHD Risk Calculator.',
  },
  {
    link: 'http://www.medi-mouse.com/graphics/scat3-child.pdf',
    imageURL: '/images/ConcussionChild.png',
    imageAlt: 'Concussion - Child',
    title: 'Concussion: SCAT3 Child',
    description: '',
  },
  {
    link: 'http://depts.washington.edu/shfm/app.php?width=1870&height=789',
    imageURL: '/images/HeartFailure.jpg',
    imageAlt: 'Heart Failure',
    title: 'Heart Failure',
    description: 'Heart Failure Risk Calculator.',
  },
  {
    link: 'https://www.hardingcenter.de/en/transfer-and-impact/fact-boxes',
    imageURL: '/images/HardingBox.png',
    imageAlt: 'Harding Logo',
    title: 'Harding Fact Boxes',
    description: '',
  },
  {
    link: 'http://www.medi-mouse.com/graphics/GAFScale.pdf',
    imageURL: '/images/MentalHealth.png',
    imageAlt: 'Mental Illness',
    title: 'Mental Illness',
    description: 'GAF Scale.',
  },
  {
    link: 'https://www.sheffield.ac.uk/FRAX/tool.aspx?country=9',
    imageURL: '/images/Osteoporosis.png',
    imageAlt: 'Osteoporosis',
    title: 'Osteoporosis: FRAX.',
    description: '',
  },
  {
    link: 'https://painbc.ca/health-professionals/assessment-tools',
    imageURL: '/images/PainBC.jpg',
    imageAlt: 'PainBC',
    title: 'PainBC',
    description: '',
  },
  {
    link: 'https://prostate.predict.nhs.uk/tool',
    imageURL: '/images/ProstateCancer.png',
    imageAlt: 'ProstateCancer',
    title: 'PREDICT',
    description: 'Prostate Cancer Risk Prediction tool.',
  },
  {
    link: 'http://www.medi-mouse.com/graphics/Epworth.pdf',
    imageURL: '/images/Sleep.png',
    imageAlt: 'Sleepiness',
    title: 'Epworth Sleepiness Scale',
    description: '',
  },
  {
    link: 'https://thrombosiscanada.ca/tools/',
    imageURL: '/images/Thrombosis.png',
    imageAlt: 'Thrombosis',
    title: 'Thrombosis-Anti-coagulation Tools',
    description: 'Includes CHADSvasc.',
  },
]